manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
  self:
    path: config

#west build -b nice_nano -- -DSHIELD=dolomity_left -DZMK_CONFIG="C:\Users\super\zmk-config-splitkb_dolomity\config"




